// Generated by CoffeeScript 1.6.3
(function() {
  var c,
    _this = this;

  c = require('multi-config');

  exports.setUp = function(app, cb) {
    p("START");
    return typeof cb === "function" ? cb() : void 0;
  };

  exports.tearDown = function(app, cb) {
    return typeof cb === "function" ? cb() : void 0;
  };

}).call(this);
