// Generated by CoffeeScript 1.7.1
var c, redis, shared;

c = require('multi-config');

redis = null;

shared = require("./shared");

exports.setUp = function(app, cb) {
  var missing, opts, _ref, _ref1;
  if (c.redis == null) {
    return typeof cb === "function" ? cb() : void 0;
  }
  missing = shared.missingParameters(["host", "port"], c.redis);
  if (missing) {
    return cb(new Error(missing));
  }
  opts = (_ref = (_ref1 = c.redis.opts) != null ? _ref1 : c.redis.opts) != null ? _ref : {};
  app.redis = redis.createClient(parseInt(c.redis.port), c.redis.host, opts);
  return typeof cb === "function" ? cb() : void 0;
};

exports.tearDown = function(app, cb) {
  if (app.redis == null) {
    return typeof cb === "function" ? cb() : void 0;
  }
  if (redis == null) {
    redis = require('redis');
  }
  app.redis.end();
  delete app.redis;
  return typeof cb === "function" ? cb() : void 0;
};
