// Generated by CoffeeScript 1.7.1
var c, shared, zerorpc;

c = require('multi-config');

shared = require("./shared");

zerorpc = null;

exports.setUp = function(app, cb) {
  var host, opts;
  if (c.zerorpc == null) {
    return typeof cb === "function" ? cb() : void 0;
  }
  if (zerorpc == null) {
    zerorpc = require('zerorpc');
  }
  opts = c.zerorpc.opts != null ? c.zerorpc.opts : {};
  host = c.zerorpc.host != null ? c.zerorpc.host : "tcp://127.0.0.1:4242";
  if (typeof c.zerorpc === "string") {
    host = c.zerorpc;
  }
  app.zerorpc = new zerorpc.Client();
  app.zerorpc.connect(host);
  return typeof cb === "function" ? cb() : void 0;
};

exports.tearDown = function(app, cb) {
  if (app.zerorpc == null) {
    return typeof cb === "function" ? cb() : void 0;
  }
  app.zerorpc.close();
  delete app["zerorpc"];
  return typeof cb === "function" ? cb() : void 0;
};
