// Generated by CoffeeScript 1.6.3
(function() {
  var config;

  config = require('node-config');

  exports.setUp = function(app, cb) {
    return typeof cb === "function" ? cb() : void 0;
  };

  exports.tearDown = function(app, cb) {
    return typeof cb === "function" ? cb() : void 0;
  };

}).call(this);
