// Generated by CoffeeScript 1.6.3
(function() {
  var keys;

  keys = ["ETCD_HOST", "POSTGRES_HOST", "POSTGRES_PORT", "REDIS_PORT", "REDIS_HOST", "LOGGLY_CUSTOMER_TOKEN", "LOGGLY_SUBDOMAIN", "LOGGLY_USERNAME", "LOGGLY_PASSWORD", "RABBIT_HOST", "RABBIT_PORT"];

}).call(this);
