// Generated by CoffeeScript 1.6.3
(function() {
  var amqp, config, conn, exchanges, queues;

  config = require('node-config');

  amqp = require('amqp');

  conn = function() {};

  exchanges = function() {};

  queues = function() {};

  exports.setUp = function(app, cb) {
    return typeof cb === "function" ? cb() : void 0;
  };

  exports.tearDown = function(app, cb) {
    return typeof cb === "function" ? cb() : void 0;
  };

}).call(this);
