// Generated by CoffeeScript 1.6.3
(function() {
  var amqp, config, conn, exchanges, extend, queues;

  config = require('node-config');

  amqp = require('amqp');

  extend = require('extend');

  /*
  Assumptions
    1 rabbit connection
    1+ queue
    1+ exchange
  
  Example
    rabbit
      host:
      port:
      queues: [
        name:
        exchange: 
        opts:
      ]
      exchanges: [
        name:
        opts:
      ]
  */


  conn = {
    setUp: function(app, cb) {},
    tearDown: function(app, cb) {}
  };

  exchanges = {
    setUp: function(app, obj, cb) {},
    tearDown: function(queue, cb) {}
  };

  queues = function(app) {};

  exports.setUp = function(app, cb) {
    if (app.rabbit == null) {
      return typeof cb === "function" ? cb(null, app) : void 0;
    }
    return typeof cb === "function" ? cb() : void 0;
  };

  exports.tearDown = function(app, cb) {
    return typeof cb === "function" ? cb() : void 0;
  };

}).call(this);
